# Uncomment the next line to define a global platform for your project

platform :ios, ’10.0’

target 'EjemploCocoaPods' do
  
  use_frameworks!

  # Pods for EjemploCocoaPods

	pod 'Alamofire', '~> 4.0'  
	pod 'SwiftyJSON'

end
